'use client';
import {useEffect,useState,useCallback} from 'react';
import {Box,Plus,ImageIcon,Upload,Package,Tag,Layers,ExternalLink,Check,Loader2,Pencil,Camera} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {Product} from '@/lib/store';
type Item=Product&{price?:number};
const money=(n:number|null|undefined)=>n==null?'Sin precio':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);
const duration=(hours:number)=>{const total=Math.round(hours*60);return `${Math.floor(total/60)} h ${total%60} min`;};
const empty:Product={id:'',name:'',description:'',hours:0,grams:0,loss:10,cost:0,retail:null,wholesale:null,image:null,published:0};
export default function Workspace({mode}:{mode:'admin'|'mayorista'|'minorista'}){
 const [timeHours,setTimeHours]=useState(''),[timeMinutes,setTimeMinutes]=useState('');
 const admin=mode==='admin';const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[edit,setEdit]=useState<Product|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[formError,setFormError]=useState(''),[hourPrice,setHourPrice]=useState(200),[kgPrice,setKgPrice]=useState(20000),[globalKg,setGlobalKg]=useState(20000),[costBusy,setCostBusy]=useState(false),[costError,setCostError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/products?mode='+mode);const data=await r.json() as Item[] & {error?:string};if(!r.ok)throw Error(data.error);setItems(data);}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar los productos.');}finally{setLoading(false);}},[mode]);useEffect(()=>{load();},[load]);
 useEffect(()=>{if(admin)fetch('/api/settings').then(async r=>{const d=await r.json() as {filamentKg:number;error?:string};if(!r.ok)throw Error(d.error);setGlobalKg(d.filamentKg);setKgPrice(d.filamentKg);}).catch(e=>setCostError(e.message));},[admin]);
 const updateFilament=async(e:React.FormEvent)=>{e.preventDefault();setCostBusy(true);setCostError('');try{const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filamentKg:globalKg})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setKgPrice(globalKg);setNotice('Costo del filamento y precios actualizados');await load();}catch(e){setCostError(e instanceof Error?e.message:'No pudimos actualizar los precios.');}finally{setCostBusy(false);}};
 const begin=(p:Product)=>{const totalMinutes=Math.round(p.hours*60);setTimeHours(totalMinutes?String(Math.floor(totalMinutes/60)):'');setTimeMinutes(totalMinutes?String(totalMinutes%60):'');const cost=Math.round((p.hours*200+p.grams*kgPrice/1000*(1+p.loss/100))*100)/100;setEdit({...p,cost,wholesale:cost>0?Math.round(cost*3/500)*500:null});setFormError('');setHourPrice(200);};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!admin||!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'start_product_creation',description:'Abre el formulario de un nuevo producto sin guardarlo ni publicarlo.',inputSchema:{type:'object',properties:{name:{type:'string',maxLength:160}},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const v=input as {name?:string};if(!v||typeof v!=='object'||(v.name!==undefined&&typeof v.name!=='string')||(v.name?.length||0)>160)throw Error('Nombre inválido');begin({...empty,name:v.name||''});return {formOpened:true};}},{signal:lifecycle.signal})).catch(console.error);return ()=>lifecycle.abort();},[admin]);
 const change=(key:keyof Product,value:unknown)=>setEdit(p=>{if(!p)return p;const next={...p,[key]:value};if(['hours','grams','loss','cost'].includes(key)){next.cost=Math.round((next.hours*200+next.grams*kgPrice/1000*(1+next.loss/100))*100)/100;next.wholesale=next.cost>0?Math.round(next.cost*3/500)*500:null;}return next;});
 const changeTime=(part:'hours'|'minutes',value:string)=>{if(value!==''&&!/^\d+$/.test(value))return;if(part==='minutes'&&Number(value)>59)return;if(part==='hours'&&Number(value)>100000)return;const normalized=value===''?'':String(Number(value));if(part==='hours')setTimeHours(normalized);else setTimeMinutes(normalized);change('hours',Number(part==='hours'?normalized:timeHours)+Number(part==='minutes'?normalized:timeMinutes)/60);};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setFormError('');try{const r=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);setEdit(null);setNotice('Producto guardado');await load();}catch(e){setFormError(e instanceof Error?e.message:'No pudimos guardar el producto.');}finally{setBusy(false);}};
 const upload=async(file?:File)=>{if(!file)return;if(file.size>4*1024*1024){setFormError('La foto debe pesar menos de 4 MB.');return;}setUploading(true);setFormError('');try{const form=new FormData();form.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:form});const data=await r.json() as {error?:string;url:string};if(!r.ok)throw Error(data.error);change('image',data.url);}catch(e){setFormError(e instanceof Error?e.message:'No pudimos cargar la foto.');}finally{setUploading(false);}};
 const published=items.filter(p=>p.published).length;
 return <div className={admin?'app':'catalog-app'}>
 {admin&&<aside className="sidebar"><a href="/admin" className="brand"><span className="brandmark"><Layers size={22}/></span><span>SUDvenirs</span></a><div className="side-caption">TU TALLER</div><div className="side-active"><Package size={19}/> Productos</div><div className="side-caption catalogs-caption">CATÁLOGOS</div><a className="side-link" href="/minorista" target="_blank" rel="noreferrer"><Tag size={18}/> Minorista<ExternalLink size={14}/></a><a className="side-link" href="/mayorista" target="_blank" rel="noreferrer"><Box size={18}/> Mayorista<ExternalLink size={14}/></a><a className="side-link logout" href="/api/auth/logout">Cerrar sesión</a><div className="side-bottom"><span className="avatar">3D</span><div>Administración<small>Tu catálogo, a tu ritmo</small></div></div></aside>}
 <main className="main">
 {!admin&&<header className="catalog-header"><div className="catalog-brand"><img src="/catalogo/logo.png" alt="SUDvenirs"/></div><span className="catalog-label">{mode==='mayorista'?'Venta mayorista':'Venta minorista'}</span></header>}
 <div className="topline"><div><div className="eyebrow">{admin?'PRODUCTOS Y PRECIOS':'IMPRESIÓN 3D'}</div><h1>{admin?'Tu catálogo, en orden.':mode==='mayorista'?'Catálogo por mayor':'Catálogo por menor'}</h1><p>{admin?'Cargá tus productos y elegí qué mostrar en cada catálogo.':mode==='mayorista'?'El precio por mayor depende de la cantidad.':'Estamos en Ituzaingó. Hacemos envíos por la zona; consultá el precio.'}</p></div>{admin&&<button className="primary" onClick={()=>begin(empty)}><Plus size={19}/>Nuevo producto</button>}</div>
 {admin&&<><section className="metrics"><div><span>Productos</span><strong>{items.length.toString().padStart(2,'0')}</strong><Package size={20}/></div><div><span>Publicados</span><strong>{published.toString().padStart(2,'0')}</strong><Tag size={20}/></div><div><span>Pendientes de revisión</span><strong>{(items.length-published).toString().padStart(2,'0')}</strong><Pencil size={20}/></div></section><form className="filament-settings" onSubmit={updateFilament}><div><h2>Costo del filamento</h2><p>Al guardar, se ajustan los costos y el mayorista (costo × 3, al múltiplo de $500 más cercano). El minorista se mantiene. Tiempo de impresión: $200/h.</p></div><label>ARS por kilo<input type="number" min="0.01" step="0.01" required value={globalKg} onChange={e=>setGlobalKg(Number(e.target.value))}/></label><button className="primary" disabled={costBusy}>{costBusy?'Actualizando…':'Actualizar precios'}</button>{costError&&<p className="form-error" role="alert">{costError}</p>}</form><div className="import-note"><span className="note-icon"><Layers size={20}/></span><div><strong>Empezá con tu primer producto</strong><p>Cargá los datos de producción, elegí el precio minorista y agregá una foto. El mayorista se calcula automáticamente.</p></div></div></>}
 {notice&&<div role="status" className="success"><Check size={17}/>{notice}<button onClick={()=>setNotice('')} aria-label="Cerrar aviso">×</button></div>}
 {loading?<div className="empty-state" role="status"><Loader2 className="spin"/>Cargando productos…</div>:error?<div className="empty-state" role="alert"><h2>No pudimos cargar el catálogo</h2><p>{error}</p><button className="secondary" onClick={load}>Reintentar</button></div>:admin?<section className="product-section"><div className="section-heading"><h2>Todos los productos</h2><span>{items.length} productos</span></div><div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead>Costo</TableHead><TableHead>Minorista</TableHead><TableHead>Mayorista</TableHead><TableHead>Estado</TableHead><TableHead><span className="sr-only">Editar</span></TableHead></TableRow></TableHeader><TableBody>{items.map(p=><TableRow key={p.id}><TableCell><div className="product-name"><div className="thumb">{p.image?<img src={p.image} alt=""/>:<ImageIcon size={20}/>}</div><div><strong>{p.name}</strong><small>{p.grams} g · {duration(p.hours)} de impresión</small></div></div></TableCell><TableCell className="cost">{money(p.cost)}</TableCell><TableCell className="price">{money(p.retail)}</TableCell><TableCell className={p.wholesale==null?'missing':'price'}>{money(p.wholesale)}</TableCell><TableCell><span className={p.published?'badge published':'badge draft'}>{p.published?'Publicado':'Borrador'}</span></TableCell><TableCell><button className="edit-button" onClick={()=>begin(p)} aria-label={'Editar '+p.name}><Pencil size={17}/></button></TableCell></TableRow>)}</TableBody></Table></div></section>:items.length?<section className="catalog-grid">{items.map(p=><article className="product-card" key={p.id}><div className="product-photo">{p.image?<img src={p.image} alt={p.name}/>:<div className="no-photo"><ImageIcon size={32}/><span>Foto pendiente</span></div>}</div><div className="card-content"><h2>{p.name}</h2>{p.description&&<p>{p.description}</p>}<strong>{money(p.price)}</strong><small>Precio por unidad · ARS</small></div></article>)}</section>:<div className="empty-state"><Package size={38}/><h2>Estamos preparando el catálogo</h2><p>Los productos estarán disponibles próximamente.</p></div>}
 <footer>{admin?'Los costos y datos de producción solo se muestran en la administración.':'Catálogo de productos · Impresión 3D'}</footer>
 </main>
 <Dialog open={!!edit} onOpenChange={open=>{if(!open&&!busy&&!uploading)setEdit(null);}}><DialogContent className="editor"><DialogTitle>{edit?.id?'Editar producto':'Nuevo producto'}</DialogTitle><DialogDescription>Cargá la información y los precios de tu producto.</DialogDescription>{edit&&<form onSubmit={save}>
 <div className="form-main"><div className="photo-editor"><div className="photo-preview">{edit.image?<img src={edit.image} alt="Referencia del producto"/>:<><Camera size={36}/><span>Foto del producto</span></>}</div><label className="upload-button"><Upload size={17}/>{uploading?'Subiendo…':'Seleccionar foto'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading||busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}}/></label><small>JPG, PNG o WebP · Hasta 4 MB</small>{edit.image&&<button type="button" className="text-button" onClick={()=>change('image',null)}>Quitar foto</button>}</div><div className="fields"><label>Nombre del producto<input required maxLength={160} value={edit.name} onChange={e=>change('name',e.target.value)} placeholder="Ej. Soporte para auriculares"/></label><label>Descripción<textarea maxLength={3000} value={edit.description} onChange={e=>change('description',e.target.value)} placeholder="Medidas, materiales, colores disponibles…" rows={3}/></label><div className="field-row"><label>Precio minorista (ARS)<input type="number" min="0" step="0.01" value={edit.retail??''} onChange={e=>change('retail',e.target.value===''?null:Number(e.target.value))}/></label><label>Mayorista automático (ARS)<input type="number" readOnly value={edit.wholesale??''} placeholder="Cargá tiempo y peso"/><small className="formula-help">Costo × 3 · Redondeo a $500</small></label></div></div></div>
 <div className="cost-editor"><h3>Costos de producción <span>Solo para vos</span></h3><div className="field-row three"><div><strong style={{fontSize:13}}>Tiempo de impresión</strong><div className="field-row"><label>Horas<input type="text" inputMode="numeric" pattern="[0-9]*" placeholder="0" aria-label="Horas de impresión" value={timeHours} onChange={e=>changeTime('hours',e.target.value)}/></label><label>Minutos<input type="text" inputMode="numeric" pattern="[0-9]*" placeholder="0" aria-label="Minutos de impresión" value={timeMinutes} onChange={e=>changeTime('minutes',e.target.value)}/></label></div><small>Minutos: de 0 a 59</small></div><label>Peso (gramos)<input type="number" min="0" step="0.01" placeholder="0" value={edit.grams||''} onChange={e=>change('grams',Number(e.target.value))}/></label><label>Pérdida (%)<input type="number" min="0" max="100" step="0.1" value={edit.loss} onChange={e=>change('loss',Number(e.target.value))}/></label></div><div className="field-row three"><label>Costo por hora (ARS)<input type="number" min="0" value={hourPrice} readOnly/></label><label>Filamento por kg (ARS)<input type="number" min="0" value={kgPrice} readOnly/></label><label>Costo total (ARS)<input type="number" min="0" step="0.01" value={edit.cost} readOnly/></label></div><div className="recalc"><span>Minorista sugerido: <strong>{money(edit.wholesale==null?null:Math.round(edit.wholesale*1.3/500)*500)}</strong> <small>(mayorista + 30%)</small></span><button type="button" className="secondary" onClick={()=>change('cost',Math.round((edit.hours*hourPrice+edit.grams*kgPrice/1000*(1+edit.loss/100))*100)/100)}>Recalcular costo</button><button type="button" className="text-button" onClick={()=>change('retail',edit.wholesale==null?null:Math.round(edit.wholesale*1.3/500)*500)}>Usar sugerido</button></div></div>
 <div className="publish-row"><div><strong>Publicar en los catálogos</strong><p>Cada catálogo muestra únicamente su precio. Sin precio, el producto no aparece en ese catálogo.</p></div><Switch checked={!!edit.published} onCheckedChange={v=>change('published',v?1:0)} aria-label="Publicar producto"/></div>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy||uploading} onClick={()=>setEdit(null)}>Cancelar</button><button className="primary" disabled={busy||uploading}>{busy?<Loader2 className="spin" size={18}/>:<Check size={18}/>}Guardar producto</button></div>
 </form>}</DialogContent></Dialog></div>;
}
